version: '3.8'

services:
  # ---------- Zookeeper ----------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      JMX_PORT: 9997
    ports:
      - "2181:2181"
      - "9997:9997"   # JMX for Prometheus
    networks:
      - microservices-network

  zookeeper-jmx-exporter:
    image: bitnami/jmx-exporter:latest
    container_name: zookeeper-jmx-exporter
    ports:
      - "9404:9404"
    volumes:
      - ./monitoring/jmx/zookeeper.yml:/config.yml
    command:
      - "9404"
      - "/config.yml"
    depends_on:
      - zookeeper
    networks:
      - microservices-network



  # ---------- Kafka ----------
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_JMX_PORT: 9999
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"   # JMX for Prometheus
    networks:
      - microservices-network

  kafka-jmx-exporter:
    image: bitnami/jmx-exporter:latest
    container_name: kafka-jmx-exporter
    ports:
      - "9308:9308"
    volumes:
      - ./monitoring/jmx/kafka.yml:/config.yml
    command:
      - "9308"
      - "/config.yml"
    depends_on:
      - kafka
    networks:
      - microservices-network

  # ---------- Kafdrop ----------
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    ports:
      - "9001:9000"
    depends_on:
      - kafka
    networks:
      - microservices-network

  # ---------- MongoDB ----------
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    command: bash -c "mongod --replSet rs0 --bind_ip_all"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network

  mongo-init:
    image: mongo:7.0
    container_name: mongo-init
    depends_on: [mongodb]
    entrypoint: >
      /bin/sh -c "
      until mongosh --host mongodb:27017 --eval 'db.adminCommand({ ping: 1 })' >/dev/null 2>&1; do
        echo 'Mongo not ready.'; sleep 2;
      done;
      mongosh --host mongodb:27017 --eval 'rs.initiate({_id:\"rs0\",members:[{_id:0,host:\"mongodb:27017\"}]})' || true;
      echo 'rs initiated';
      "
    networks:
      - microservices-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - microservices-network


  # ---------- DynamoDB ----------
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/data
    networks:
      - microservices-network

  dynamodb-init:
    image: amazon/aws-cli:latest
    container_name: dynamodb-init
    depends_on:
      - dynamodb-local
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      aws dynamodb create-table --table-name UserProfiles \
        --attribute-definitions AttributeName=userId,AttributeType=S \
        --key-schema AttributeName=userId,KeyType=HASH \
        --billing-mode PAY_PER_REQUEST \
        --endpoint-url http://dynamodb-local:8000 || echo 'table exists';
      "
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: us-east-1
    networks:
      - microservices-network

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb-local
    networks:
      - microservices-network

  # ---------- Loki, Promtail ----------
  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - microservices-network

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    volumes:
      - /var/log/docker/containers:/var/log/docker/containers
      - ./monitoring/loki/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    networks:
      - microservices-network

  # ---------- Prometheus ----------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - microservices-network

  # ---------- Grafana ----------
  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
      - loki
    networks:
      - microservices-network

  # ---------- profile-api-service ----------
  profile-api-service:
    build:
      context: ./profile-api-service
      dockerfile: Dockerfile
    container_name: profile-api-service
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
      AWS_DYNAMODB_TABLE_NAME: UserProfiles
      DYNAMODB_TABLE_NAME: UserProfiles
      AWS_REGION: us-east-1
      PROFILE_API_KEY: dummy-key-for-local
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      dynamodb-local:
        condition: service_started
      dynamodb-init:
          condition: service_completed_successfully
    networks:
      - microservices-network

  # ---------- user-api-service ----------
  user-api-service:
    build:
      context: ./user-api-service
      dockerfile: Dockerfile
    container_name: user-api-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGODB_URI: mongodb://mongodb:27017/userdb?replicaSet=rs0
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_USER_CREATED_TOPIC: user-created-topic
      PROFILE_API_URL: http://profile-api-service:8081/profiles
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - kafka
      - mongo-init
    networks:
      - microservices-network

  # ---------- notification-service ----------
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    environment:
      DYNAMODB_TABLE_NAME: UserProfiles
      PROFILE_API_URL: http://profile-api-service:8081/profiles
      KAFKA_TOPIC: user-created-topic
      AWS_REGION: us-east-1
    ports:
      - "9000:8080"
    depends_on:
      - kafka
      - profile-api-service
    networks:
      - microservices-network

  # ---------- lambda-invoker ----------
  lambda-invoker:
    build:
      context: ./lambda-invoker
      dockerfile: Dockerfile
    container_name: lambda-invoker
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: user-created-topic
      LAMBDA_URL: http://notification-service:8080/2015-03-31/functions/function/invocations
      AWS_REGION: us-east-1
    depends_on:
      - kafka
      - notification-service
    networks:
      - microservices-network


volumes:
  mongodb_data:
  dynamodb_data:

networks:
  microservices-network:
    driver: bridge
