global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'profile-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['profile-api-service:8081']

  - job_name: 'user-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-api-service:8080']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-jmx-exporter:9308']

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper-jmx-exporter:9404']

